"""Generate firmware/radar_table.cpp from the official IEM n0q colour table.

tools/radar/composite_n0q.txt comes from pyIEM (src/pyiem/data/ramps/composite_n0q.txt):
coloridx, dBZ, r, g, b. The WMS paints each 0.5 dBZ step with exactly one of these
colours, so the device can map a pixel back to dBZ by exact lookup (docs/10).

Run:  python tools/radar/make_radar_table.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
rows = [ln.split(",") for ln in (ROOT / "tools/radar/composite_n0q.txt").read_text().splitlines()[1:]]
entries = {}
for _, dbz, r, g, b in rows:
    key = (int(r) << 16) | (int(g) << 8) | int(b)
    entries.setdefault(key, round(float(dbz) * 2))       # first (lowest dBZ) wins on a duplicate colour
keys = sorted(entries)
out = ["// GENERATED by tools/radar/make_radar_table.py - do not edit.",
       "// IEM n0q colour -> dBZ x2 (source: pyIEM composite_n0q.txt). Sorted by RGB for bsearch.",
       '#include "radar_model.h"', "",
       f"const RadarRamp RADAR_RAMP[{len(keys)}] = {{"]
for i in range(0, len(keys), 4):
    out.append("  " + " ".join(f"{{0x{k:06X}, {entries[k]}}}," for k in keys[i:i + 4]))
out += ["};", f"const uint16_t RADAR_RAMP_N = {len(keys)};", ""]
(ROOT / "firmware/radar_table.cpp").write_text("\n".join(out), encoding="utf-8")
print(f"{len(keys)} colours -> firmware/radar_table.cpp")
