"""Embed docs/mockups/portal/index.html (the setup portal's phone page, docs/12) into the
firmware as firmware/portal_page.cpp: GENERATED - don't hand-edit; re-run after changing the page.

The page is served byte-for-byte, split at the /*STATE*/ marker where the firmware inlines
`var S={...};` (round 1 M2: no second request that could fail).

    python tools/portal/embed_page.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "docs" / "mockups" / "portal" / "index.html"
OUT = ROOT / "firmware" / "portal_page.cpp"
MARK = "/*STATE*/"

page = SRC.read_text(encoding="utf-8")
assert page.count(MARK) == 1, "the page needs exactly one /*STATE*/ marker"
bad = [c for c in page if ord(c) > 127]
assert not bad, f"non-ASCII in the page: {bad[:5]} - use \\uXXXX escapes"
head, tail = page.split(MARK)


def c_raw(name: str, text: str) -> str:
    assert ")PAGE\"" not in text
    # extern: a namespace-scope const has internal linkage in C++
    return f'extern const char {name}[] PROGMEM;\nconst char {name}[] PROGMEM = R"PAGE({text})PAGE";\n'


OUT.write_text(
    "// GENERATED by tools/portal/embed_page.py from docs/mockups/portal/index.html - don't edit.\n"
    "// The setup portal's phone page (docs/12), split where the state is inlined.\n"
    "#include <pgmspace.h>\n\n" + c_raw("PORTAL_PAGE_HEAD", head) + c_raw("PORTAL_PAGE_TAIL", tail),
    encoding="utf-8", newline="\n")
print(f"wrote {OUT.relative_to(ROOT)}: {len(head)} + {len(tail)} bytes")
