// basemap.h - pre-rendered local map for the plane map screen.
// Data is generated by tools/basemap/make_basemap.py into basemap_data.cpp.
#pragma once

#include <Arduino.h>
#include "config.h"

#define MAP_W       320
#define MAP_H       240
#define MAP_CX      160      // observer pixel (must match make_basemap.py)
#define MAP_CY      116
#define MAP_ZOOM_N  3

// 4-bit palette indices (order == PALETTE in make_basemap.py)
enum MapPal : uint8_t {
  M_BG, M_PRIMARY, M_TRUNK, M_MOTORWAY, M_RUNWAY, M_WATER, M_TRAIL, M_TEXT,
  M_MUTED, M_DIM, M_PLANE, M_PLANE_DIM, M_ZONE, M_PANEL, M_YOU, M_WARN
};

struct MapZoom {
  const uint8_t *img;   // MAP_W*MAP_H/2 bytes, 4bpp packed like TFT_eSprite
  float pxPerNm;
};

struct MapPalette { uint16_t c[16]; };

struct MapLabel {
  const char *name;
  float lat, lon;
  bool major;           // city (vs town) / airport
};

extern const MapZoom MAP_ZOOMS[MAP_ZOOM_N];
extern const MapPalette MAP_PALETTE;
extern const MapLabel MAP_TOWNS[];
extern const uint8_t MAP_TOWN_N;
extern const MapLabel MAP_AIRPORTS[];
extern const uint8_t MAP_AIRPORT_N;

// Rain radar view (docs/10): one wide zoom + towns in population order.
extern const MapZoom RADAR_BASEMAP;
extern const MapLabel RADAR_TOWNS[];
extern const uint8_t RADAR_TOWN_N;
